language: node_js
os: linux
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - develop # build master branch only
script:
  - hexo generate &&  ls && pwd # generate static files
deploy:
  provider: pages
  token: $GH_TOKEN
  keep_history: false
  local_dir: public
  cleanup: false
  target_branch: master
  allow_empty_commit: true
  on:
    branch: develop
