language: node_js
os: linux
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - develop # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  token: $GH_TOKEN
  keep-history: true
  local-dir: public
  skip-cleanup: true
  target-branch: master
  on:
    branch: develop
